//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/26/2026 17:50:09
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace dbproba
{
    public partial class Könyv {

        public Könyv()
        {
            OnCreated();
        }

        public short Id { get; set; }

        public string Szerzők { get; set; }

        public string Cím { get; set; }

        public short KiadásÉve { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
