-- Script was generated by Devart Entity Developer, Version 7.2.104.0
-- Script date 2/21/2026 14:26:21
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Creating a table Konyvek 
-- 
use proba
CREATE TABLE Konyvek (
   Id SMALLINT NOT NULL IDENTITY,
   Szerzők NVARCHAR(4000) NOT NULL,
   Cím NVARCHAR(4000) NOT NULL,
   KiadásÉve SMALLINT NOT NULL,
   CONSTRAINT PK_Konyvek PRIMARY KEY (Id)
)
GO

